#!/usr/bin/env bash
# SSH client configuration

Host *
	PaswwordAuthentication no
	IdentityFile ~/.ssh/school
	SendEnv LANG LC_*
	HashKnownHosts yes
	GSSAPIAuthentication yes
	GSSAPIDelegateCredentials no
